version: '3'

services:
  app:
    image: webdevops/php-apache:7.4
    restart: always
    environment:
      - TZ=Asia/Jakarta
      # - APPLICATION_PATH=/app
    ports:
      - 80:80
    command: apt-get install -y npm
    # volumes:
    #   - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=admin2000
      - MYSQL_DATABASE=mikrotik
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin2000